### ISSUE TITLE
Does there exist some swift client code to use this library binding

### ISSUE THREAD

**Issue by sangeetas** [ukyg9e5r6k7gubiekd6/swift-client#1]
Hi, 
I have a question. I am trying to build this client code you provided with cURL 7.47.1. Since this is just a C library binding, I was wondering if there is some test program available to test this? 
 I am aiming for a CLI but a bit unsure of how to go about it.

**Comment by ukyg9e5r6k7gubiekd6** [comment]
Hello, have a look at my 'test-swift-client' repository - that's a command-line program which uses this library and the keystone-client library (which is another separate repository) to benchmark Swift performance. The benchmarking parts could be easily removed if all you need is a Swift CLI.
For a more full-featured Swift CLI, have a look at the Python Swift bindings. On Debian and Ubuntu, the package 'python-swiftclient' ships a Python library binding, and also a Swift CLI.
